name: pages

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'artifact containing built site'
        required: false
        type: string
        default: 'github-pages'
      path:
        description: 'path to upload'
        required: false
        type: string
        default: '.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v4
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.path }}
          name: ${{ inputs.artifact_name }}
      
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ inputs.artifact_name }}
