name: typst

on:
  workflow_call:
    inputs:
      typst_version:
        description: 'typst version to use'
        required: false
        type: string
        default: 'latest'
      source:
        description: 'source .typ file'
        required: true
        type: string
      output:
        description: 'output pdf name'
        required: false
        type: string
        default: 'document.pdf'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: JakobMelchard/.github/actions/setup-typst@main
        with:
          version: ${{ inputs.typst_version }}
      
      - name: compile
        run: typst compile "${{ inputs.source }}" "${{ inputs.output }}"
      
      - uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ${{ inputs.output }}
